import React from 'react';
import { Bell, Info, AlertTriangle, CheckCircle, X } from 'lucide-react';

interface Notification {
  id: string;
  type: 'info' | 'warning' | 'success';
  title: string;
  message: string;
  time: string;
  unread: boolean;
}

const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    type: 'warning',
    title: 'Threshold Breach Detected',
    message: 'FIN01 (Revenue) dropped below acceptable levels in Scenario "Ransomware".',
    time: '5m ago',
    unread: true,
  },
  {
    id: '2',
    type: 'success',
    title: 'Scenario Run Complete',
    message: 'Cross-scenario sweep completed across 56 models.',
    time: '12m ago',
    unread: true,
  },
  {
    id: '3',
    type: 'info',
    title: 'New Board Brief',
    message: 'A new comparative brief has been generated by Alice.',
    time: '2h ago',
    unread: false,
  }
];

export function NotificationsPanel({ onClose }: { onClose: () => void }) {
  return (
    <div className="absolute top-12 right-0 w-80 bg-surface border border-outline/20 rounded-lg shadow-2xl overflow-hidden z-50 flex flex-col animate-in fade-in slide-in-from-top-2 duration-200">
      <div className="flex items-center justify-between p-4 border-b border-outline/10 bg-surface-container-low">
        <div className="flex items-center space-x-2">
          <Bell className="w-4 h-4 text-on-surface" />
          <h3 className="font-sans text-sm font-bold text-white">Notifications</h3>
        </div>
        <button 
          onClick={onClose}
          className="text-on-surface-variant hover:text-white transition-colors"
        >
          <X className="w-4 h-4" />
        </button>
      </div>
      
      <div className="flex-1 overflow-y-auto max-h-96 flex flex-col divide-y divide-outline/10">
        {MOCK_NOTIFICATIONS.map(notif => (
          <div key={notif.id} className={`p-4 flex items-start space-x-3 transition-colors hover:bg-surface-container-low ${notif.unread ? 'bg-surface-container-low/50' : ''}`}>
            <div className="shrink-0 mt-0.5">
              {notif.type === 'warning' && <AlertTriangle className="w-4 h-4 text-mtn-yellow" />}
              {notif.type === 'success' && <CheckCircle className="w-4 h-4 text-success" />}
              {notif.type === 'info' && <Info className="w-4 h-4 text-[#3b82f6]" />}
            </div>
            <div className="flex-1">
              <div className="flex justify-between items-start mb-1">
                <h4 className={`text-sm font-sans ${notif.unread ? 'text-white font-bold' : 'text-on-surface'}`}>
                  {notif.title}
                </h4>
                {notif.unread && <span className="w-2 h-2 rounded-full bg-mtn-yellow shrink-0 mt-1.5" />}
              </div>
              <p className="text-xs text-on-surface-variant leading-relaxed mb-2 font-sans">
                {notif.message}
              </p>
              <span className="text-[10px] font-mono text-outline tracking-widest uppercase">
                {notif.time}
              </span>
            </div>
          </div>
        ))}
      </div>
      
      <div className="p-3 border-t border-outline/10 bg-surface-container-low text-center">
        <button className="text-xs font-mono text-mtn-yellow hover:text-yellow-400 uppercase tracking-widest transition-colors">
          Mark all as read
        </button>
      </div>
    </div>
  );
}
